import { StyleSheet } from "react-native";

export const defaultThemeStyle = StyleSheet.create({
    "MainView": {
        "backgroundColor": "#663300",
        "borderColor": "#F5D000",
        "opacity": 1,
        "width": 407,
        "height": 480,
        "paddingVertical": 260,
        "paddingHorizontal": 260,
        "justifyContent": "center",
        "alignContent": "center",
        "alignItems": "center",
        "alignSelf": "center",
        "borderWidth": 9,
        "borderRadius": 128
      },
      "NavView": {
        "backgroundColor": "#2D63C8",
        "borderColor": "black",
        "opacity": 1,
        "width": 100,
        "height": 100,
        "paddingVertical": 0,
        "paddingHorizontal": 0,
        "justifyContent": "center",
        "alignContent": "center",
        "alignItems": "center",
        "alignSelf": "center",
        "borderWidth": 0,
        "borderRadius": 80
      },
      "InfoView": {},
      "Text": {
        "color": "#F5D000",
        "backgroundColor": "#2D63C8",
        "fontSize": 18,
        "fontFamily": "sans-serif",
        "textAlign": "center",
        "letterSpacing": 7,
        "lineHeight": 4,
        "borderColor": "#F5D000",
        "opacity": 0.85,
        "width": 340,
        "height": 73,
        "paddingVertical": 33,
        "paddingHorizontal": 0,
        "justifyContent": "center",
        "alignContent": "center",
        "alignItems": "center",
        "alignSelf": "center",
        "borderWidth": 9,
        "borderRadius": 46
      },
      "TitleText": {},
      "Modal": {},
      "MenuButton": {},
      "SyncButton": {},
      "InfoText": {},
      "titleText": {}
      
})

export const coolTheme = StyleSheet.create({
    "MainView": {
        "backgroundColor": "grey",
        "borderColor": "black",
        "opacity": 1,
        "width": 647,
        "height": 460,
        "paddingVertical": 0,
        "paddingHorizontal": 0,
        "justifyContent": "center",
        "alignContent": "center",
        "alignItems": "center",
        "alignSelf": "center",
        "borderWidth": 0,
        "borderRadius": 112
      },
      "NavView": {
        "backgroundColor": "grey",
        "borderColor": "black",
        "opacity": 1,
        "width": 100,
        "height": 100,
        "paddingVertical": 0,
        "paddingHorizontal": 0,
        "justifyContent": "center",
        "alignContent": "center",
        "alignItems": "center",
        "alignSelf": "center",
        "borderWidth": 0,
        "borderRadius": 0
      },
      "InfoView": {},
      "Text": {
        "color": "#66B032",
        "backgroundColor": "grey",
        "fontSize": 30,
        "fontFamily": "serif",
        "textAlign": "center",
        "letterSpacing": 10,
        "lineHeight": 50,
        "textShadowColor": "#663300",
        "textShadowRadius": 6,
        "borderColor": "black",
        "opacity": 1,
        "width": 527,
        "height": 80,
        "paddingVertical": 0,
        "paddingHorizontal": 0,
        "justifyContent": "center",
        "alignContent": "center",
        "alignItems": "center",
        "alignSelf": "center"
      },
      "TitleText": {},
      "Modal": {},
      "MenuButton": {},
      "SyncButton": {},
      "InfoText": {},
      "titleText": {}
      
})


// "MainView": {
//     "backgroundColor": "grey",
//     "borderColor": "#663300",
//     "opacity": 1,
//     "width": 500,
//     "height": 273,
//     "paddingVertical": 147,
//     "paddingHorizontal": 0,
//     "justifyContent": "center",
//     "alignContent": "center",
//     "alignItems": "center",
//     "alignSelf": "center",
//     "borderWidth": 14,
//     "borderRadius": 44
//   },
//   "NavView": {
//     "backgroundColor": "grey",
//     "borderColor": "black",
//     "opacity": 1,
//     "width": 320,
//     "height": 100,
//     "paddingVertical": 0,
//     "paddingHorizontal": 0,
//     "justifyContent": "center",
//     "alignContent": "center",
//     "alignItems": "center",
//     "alignSelf": "center",
//     "borderWidth": 0,
//     "borderRadius": 0
//   },
//   "InfoView": {},
//   "Text": {
//     "color": "#663300",
//     "backgroundColor": "#2D63C8",
//     "fontSize": 15,
//     "fontFamily": "serif",
//     "textAlign": "center",
//     "letterSpacing": 0,
//     "lineHeight": 24,
//     "borderColor": "black",
//     "opacity": 1,
//     "width": 380,
//     "height": 53,
//     "paddingVertical": 0,
//     "paddingHorizontal": 0,
//     "justifyContent": "center",
//     "alignContent": "center",
//     "alignItems": "center",
//     "alignSelf": "center",
//     "borderWidth": 7,
//     "borderRadius": 4
//   },
//   "TitleText": {},
//   "Modal": {},
//   "MenuButton": {},
//   "SyncButton": {},
//   "InfoText": {},
//   "titleText": {}

